version: '3'

services:
    appserver:
        build:
            context: ./appserver
            dockerfile: DockerfileLocal
        ports:
            - "8080:8080"
        image: appserver
        container_name: appserver
        restart: unless-stopped
        networks:
            - app-network
    frontend:
        build:
            context: ./frontend
            dockerfile: DockerfileLocal
        ports:
            - "3000:3000"
        image: frontend
        container_name: frontend
        restart: unless-stopped
        networks:
            - app-network
networks:
    app-network:
        driver: bridge
