version: '3'

services:
    appserver:
        build:
            context: ./appserver
            dockerfile: DockerfileLocal
        ports:
            - "8080:8080"
        image: appserver
        container_name: appserver
        restart: unless-stopped
        networks:
            - app-network
networks:
    app-network:
        driver: bridge
